version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    image: atmakurikirankumar/frontend
    ports:
    - "3000:3000"
    stdin_open: true
    volumes:
    - /app/node_modules
    - .:/app
    networks:
      - docker-travis
    environment:
      - CHOKIDAR_USEPOLLING=true
  unittests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: unittest
    image: atmakurikirankumar/frontend
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - docker-travis
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]
networks:
  docker-travis:
    driver: bridge